import { useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, Search, Volume2 } from 'lucide-react';
import { V2 } from '../../engine/v2';
import { dueWords, posOf, speak } from '../learner/learning';
export default function Review({ words, mastery, confusions = {}, learner = {}, onRate, onStart, onPractice, onAsk, onNavigate, voiceRate = 1 }) {
 const [view,setView]=useState('overview'), [search,setSearch]=useState(''), [filter,setFilter]=useState('all'), [selected,setSelected]=useState(null), [deck,setDeck]=useState([]), [index,setIndex]=useState(0), [revealed,setRevealed]=useState(false);
 const weak=w=>!!mastery[w.word]?.total && mastery[w.word]?.lastResult!=='correct';
 const weakCount=words.filter(weak).length, due=dueWords(words,mastery,learner.reviews), pairs=Object.entries(confusions).sort((a,b)=>(b[1]?.count||b[1]||0)-(a[1]?.count||a[1]||0)).slice(0,8);
 const filtered=useMemo(()=>words.filter(w=>(!search || (w.word+' '+w.meaning+' '+(w.units || []).join(' ')).toLowerCase().includes(search.toLowerCase())) && (filter==='all' || (filter==='weak'?weak(w):filter==='learning'?!!mastery[w.word]?.total&&V2.stage(mastery[w.word])!=='Mastered':filter==='new'?!mastery[w.word]?.total:V2.stage(mastery[w.word])==='Mastered'))),[words,mastery,search,filter]);
 function startCards(){setDeck(due);setIndex(0);setRevealed(false);setView('cards');}
 if(selected) {const stats=mastery[selected.word] || {}, pos=posOf(selected);return <section className="lq-word-detail"><button className="lq-back" onClick={()=>setSelected(null)}><ArrowLeft/> Word bank</button><small>{V2.stage(stats).toUpperCase()}</small><h2>{selected.word}</h2><p className="lq-muted">{selected.phonetic || selected.pronunciation || ''} · {Array.isArray(pos)?pos.join(' / '):pos}</p><button className="lq-secondary" onClick={()=>speak(selected.word,voiceRate)}><Volume2/> Hear it</button><p>{selected.meaning}</p><blockquote>{selected.situation || selected.example}</blockquote>{selected.wordFamily?.length>0 && <><h3>Word family</h3><p>{selected.wordFamily.map(w=>typeof w==='string'?w:w.word).join(', ')}</p></>}{stats.total>0 && <><h3>Your learning history</h3><p>{stats.correct || 0} correct of {stats.total} attempts · {stats.spellingMisses || 0} spelling slips</p>{stats.recentResults?.slice(-4).reverse().map((r,i)=><p key={i} className="lq-history-line">{r.correct?'Correct answer':'Needs more practice'}<small>{r.at ? new Date(r.at).toLocaleDateString() : ''}</small></p>)}</>}<div className="lq-unit-actions"><button className="lq-primary" onClick={()=>onPractice(selected)}>Practise this word</button><button className="lq-secondary" onClick={()=>onAsk(selected.word)}>Explore with AI</button></div></section>;}
 if(view==='cards') { const word=deck[index]; if(!word)return <section className="lq-empty"><BookOpen size={48}/><h2>Review complete</h2><p>{deck.length} words revisited. Your self-ratings set the next review date; question practice builds mastery.</p><button className="lq-primary" onClick={()=>setView('overview')}>Done</button></section>;return <section className="lq-review-card"><div className="lq-page-heading"><button className="lq-back" onClick={()=>setView('overview')}><ArrowLeft/> Review</button><small>{index+1} / {deck.length}</small></div><small>{V2.stage(mastery[word.word])}</small><h2>{word.word}</h2><button className="lq-secondary" onClick={()=>speak(word.word,voiceRate)}><Volume2/> Listen</button>{revealed?<><p>{word.meaning}</p><blockquote>{word.situation}</blockquote><h3>How well did you remember it?</h3><div className="lq-rating-grid">{[['again','1 min'],['hard','10 min'],['good','1 day'],['easy','4 days']].map(([rating,label])=><button className="lq-secondary" key={rating} onClick={()=>{onRate(word.word,rating);setIndex(i=>i+1);setRevealed(false);}}>{rating}<small>{label}</small></button>)}</div></>:<button className="lq-primary" onClick={()=>setRevealed(true)}>Reveal meaning</button>}</section>;}
 return <section><div className="lq-page-heading"><div><small>KEEP WHAT YOU LEARN</small><h2>{view==='bank'?'Word bank':'Review'}</h2><p>{view==='bank'?words.length+' words in your collection':'A little review keeps your English with you.'}</p></div><button className="lq-secondary" onClick={()=>setView(v=>v==='bank'?'overview':'bank')}>{view==='bank'?'Review':'Word bank'}</button></div>
 {view==='overview'?<><div className="lq-summary-tiles"><div><b>{due.length}</b><span>Due today</span></div><div><b>{weakCount}</b><span>Weak words</span></div><div><b>{pairs.length}</b><span>Confusions</span></div></div><h3>Words you mix up</h3>{pairs.length?<div className="lq-content-list">{pairs.map(([key,v])=><article key={key}><strong>{key.replace(/\|\||::|\|/g,' ⇄ ')}</strong><small>{v.count || v} mix-ups</small></article>)}</div>:<p className="lq-muted">No mix-ups recorded yet.</p>}<div className="lq-review-callout"><div><strong>Focused question practice</strong><p>Practise weak answers. No hearts needed.</p></div><button className="lq-primary" onClick={onStart} disabled={!weakCount}>Start practice</button></div><div className="lq-review-callout"><div><strong>{due.length} words due</strong><p>Recall the meaning, reveal, then rate your memory.</p></div><button className="lq-primary" disabled={!due.length} onClick={startCards}>Start review</button></div></>:<><label className="lq-search"><Search size={18}/><input aria-label="Search word bank" placeholder="Search words, meanings or units" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="lq-tabs" role="group" aria-label="Filter words">{['all','weak','learning','new','mastered'].map(t=><button key={t} aria-pressed={t===filter} onClick={()=>setFilter(t)}>{t}</button>)}</div><div className="lq-content-list">{filtered.map(w=><button className="lq-word-row" key={w.word} onClick={()=>setSelected(w)}><strong>{w.word}</strong><span>{w.meaning}</span><small>{weak(w)?'Needs practice':V2.stage(mastery[w.word])}</small></button>)}</div>{!filtered.length && <p>No matching words. Try a different filter.</p>}</>}
 <button className="lq-back" onClick={()=>onNavigate('levels')}>Back to journey</button></section>;
}
