import { useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, Search } from 'lucide-react';
import { V2 } from '../../engine/v2';
export default function Review({ words, mastery, onStart, onAsk, onNavigate }) {
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(null);
 const weak=w=>mastery[w.word]?.lastResult && mastery[w.word].lastResult!=='correct';
 const weakCount=words.filter(weak).length;
 const filtered=useMemo(()=>words.filter(w=>(!search || `${w.word} ${w.meaning}`.toLowerCase().includes(search.toLowerCase())) && (filter==='all' || (filter==='weak'?weak(w):filter==='new'?!mastery[w.word]?.total:V2.stage(mastery[w.word])==='Mastered'))),[words,mastery,search,filter]);
 if(selected) return <section className="lq-word-detail"><button className="lq-back" onClick={()=>setSelected(null)}><ArrowLeft/> Word bank</button><small>{selected.partsOfSpeech?.join(' / ')}</small><h2>{selected.word}</h2><p>{selected.meaning}</p><blockquote>{selected.situation}</blockquote>{selected.wordFamily?.length>0 && <p>Word family: {selected.wordFamily.map(w=>typeof w==='string'?w:w.word).join(', ')}</p>}<button className="lq-primary" onClick={()=>onAsk(selected.word)}>Explore this word</button></section>;
 return <section><div className="lq-page-heading"><div><small>KEEP WHAT YOU LEARN</small><h2>Review & word bank</h2><p>{words.length} words in your collection</p></div><BookOpen size={36}/></div><div className="lq-review-callout"><div><strong>{weakCount} words need practice</strong><p>Focus on the words you missed.</p></div><button className="lq-primary" disabled={!weakCount} onClick={onStart}>Start review</button></div><label className="lq-search"><Search size={18}/><input aria-label="Search word bank" placeholder="Search words or meanings" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="lq-tabs" role="group" aria-label="Filter words">{['all','weak','new','mastered'].map(t=><button key={t} aria-pressed={t===filter} onClick={()=>setFilter(t)}>{t}</button>)}</div><div className="lq-content-list">{filtered.map(w=><button className="lq-word-row" key={w.word} onClick={()=>setSelected(w)}><strong>{w.word}</strong><span>{w.meaning}</span><small>{weak(w)?'Needs practice':V2.stage(mastery[w.word])}</small></button>)}</div>{!filtered.length && <p>No matching words. Try a different filter.</p>}<button className="lq-secondary" onClick={()=>onNavigate('levels')}>Back to journey</button></section>;
}
