import { useState } from 'react';
import { ArrowLeft, Check, KeyRound, UserRound } from 'lucide-react';
import { useAuth } from '../../lib/auth';

export default function Account({ learner, onSave, onBack, onSignOut }) {
  const auth=useAuth(), [name,setName]=useState(learner.displayName || auth.profile?.username || ''), [password,setPassword]=useState(''), [confirm,setConfirm]=useState(''), [status,setStatus]=useState(''), [busy,setBusy]=useState(false);
  async function save(e) {e.preventDefault();setStatus('');setBusy(true);try {if(password){if(password!==confirm)throw Error('The passwords do not match.');await auth.changePassword(password);setPassword('');setConfirm('');}onSave({...learner,displayName:name.trim().slice(0,60)});setStatus('Account preferences saved.');}catch(e){setStatus(e.message);}finally{setBusy(false);}}
  return <section className="lq-account"><button className="lq-back" onClick={onBack}><ArrowLeft/> Profile</button><h2>Account</h2><div className="lq-avatar"><UserRound size={36}/></div><form onSubmit={save}><label className="lq-field">Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={60} required autoComplete="nickname"/></label><label className="lq-field">Username<input value={auth.profile?.username || ''} readOnly/></label><p className="lq-muted">Your username is used to sign in. Your display name personalises this account.</p><h3><KeyRound size={18}/> Change password</h3><label className="lq-field">New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} autoComplete="new-password"/></label><label className="lq-field">Confirm new password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" required={!!password}/></label><button className="lq-primary" disabled={busy}>{busy?'Saving…':<><Check size={18}/> Save changes</>}</button>{status && <p role="status">{status}</p>}</form><button className="lq-back" onClick={onSignOut}>Log out</button><p className="lq-muted">To change your username or remove your account, contact the administrator.</p></section>;
}
