import { useEffect, useRef, useState } from 'react';
import { Mic, Volume2, X } from 'lucide-react';
import { speak } from './learning';

export default function InteractiveAnswer({q,draft,onChange,disabled,onSubmit,rate=1}) {
 const [message,setMessage]=useState(''), [listening,setListening]=useState(false), [left,setLeft]=useState(null), recognition=useRef(null);
 useEffect(()=>()=>{recognition.current?.abort();window.speechSynthesis?.cancel();},[q.id]);
 if(q.type==='match') {const matched=draft.selected||[];function pair(meaning){if(!left)return;const candidate=left+' ↔ '+meaning;onChange({...draft,selected:[...matched,candidate]});setLeft(null);}return <div><div className="lq-match-grid">{q.pairs.map(p=><div key={p.word}><button disabled={disabled||matched.some(x=>x.startsWith(p.word+' ↔ '))} className={'lq-secondary '+(left===p.word?'selected':'')} aria-pressed={left===p.word} onClick={()=>setLeft(p.word)}>{p.word}</button><button disabled={disabled||matched.some(x=>x.endsWith(' ↔ '+q.meanings[q.pairs.indexOf(p)]))} className="lq-secondary" onClick={()=>pair(q.meanings[q.pairs.indexOf(p)])}>{q.meanings[q.pairs.indexOf(p)]}</button></div>)}</div><p>{q.pairs.length-matched.length} pairs left</p><div className="lq-token-answer">{matched.map(pair=><button key={pair} disabled={disabled} onClick={()=>onChange({...draft,selected:matched.filter(x=>x!==pair)})}>{pair}<X size={12}/></button>)}</div><p className="lq-muted">Tap a completed pair to undo it.</p></div>;}
 if(q.builder) {const used=draft.tokenIds||[], text=used.map(i=>q.tokens[i]).join(' ');return <div><div className="lq-token-answer" aria-label="Built sentence">{used.map((id,i)=><button key={i} disabled={disabled} onClick={()=>{const ids=used.filter((_,j)=>j!==i);onChange({...draft,tokenIds:ids,text:ids.map(k=>q.tokens[k]).join(' ')});}}>{q.tokens[id]}</button>)}</div><div className="lq-token-bank">{q.tokens.map((token,i)=><button key={i} className="lq-secondary" disabled={disabled||used.includes(i)} onClick={()=>onChange({...draft,tokenIds:[...used,i],text:(text+' '+token).trim()})}>{token}</button>)}</div><label className="lq-field">Or type the sentence<input aria-label="Your answer" disabled={disabled} value={draft.text||''} onChange={e=>onChange({...draft,text:e.target.value,tokenIds:[]})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();onSubmit();}}}/></label></div>;}
 const speech=q.type==='speech';
 function listen(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){setMessage('Speech recognition is unavailable. You can type the sentence instead.');return;}const r=new Recognition();recognition.current=r;r.lang='en-US';r.interimResults=false;r.onresult=e=>{onChange({...draft,text:e.results[0][0].transcript});setMessage('Check the transcript before submitting.');};r.onerror=e=>{setMessage(e.error==='not-allowed'?'Microphone access was declined. Type the sentence or skip.':'Could not hear you. Try again or type the sentence.');setListening(false);};r.onend=()=>setListening(false);try{r.start();setListening(true);}catch{setMessage('Could not start the microphone. Try typing instead.');}}
 return <div>{speech && <blockquote className="lq-speech-text">{q.speechText}</blockquote>}<div className="lq-audio-controls"><button className="lq-audio-play" aria-label={speech?'Hear the example':'Play question audio'} onClick={()=>{if(!speak(q.audio||q.speechText,rate))setMessage('Audio is unavailable. Skip this question and try another activity.');}}><Volume2 size={34}/></button><button className="lq-secondary" onClick={()=>speak(q.audio||q.speechText,.5)}>0.5×</button>{speech && <button disabled={disabled} className="lq-primary" onClick={()=>{if(listening){recognition.current?.stop();setListening(false);}else listen();}}><Mic/>{listening?'Stop listening':'Speak now'}</button>}</div>{message&&<p role="status">{message}</p>}<label className="lq-field">{speech?'What the browser heard':'Your answer'}<input autoComplete="off" spellCheck={false} aria-label="Your answer" value={draft.text||''} disabled={disabled} onChange={e=>onChange({...draft,text:e.target.value})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();onSubmit();}}}/></label></div>;
}
